name: rs100_discussion
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab=4.0.8
  - matplotlib=3.8.1
  - numpy=1.26.0
  - pandas=2.1.3
  - openpyxl=3.1.2
  - fredapi=0.4.2
  - statsmodels=0.14.0
  - pip
  - pip:
    - pandas-datareader==0.10.0
    - fredpy==3.2.8
